version: '2'

services:

  # Development mode with latest taf
  coordinator:
    image: stargateio/coordinator-dse-next:v2.1.0-BETA-9
    networks:
      - stargate
    ports:
      - "9042:9042"
      - "8081:8081"
      - "8090:8090"
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=sgv2-cluster
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
      - DEVELOPER_MODE=true
    healthcheck:
      test: curl -f http://localhost:8084/checker/readiness || exit 1
      interval: 15s
      timeout: 10s
      retries: 10
#
#  restapi:
#    image: stargateio/restapi:v2.1.0-BETA-9
#    depends_on:
#      - coordinator
#    networks:
#      - stargate
#    ports:
#      - "8082:8082"
#    mem_limit: 2G
#    command: /bin/bash -c "echo 'Waiting 30s for coordinator to start first... ' && sleep 30 && java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dvertx.disableURIValidation=true -Xms256m -Xmx1024m -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar"
#    environment:
#      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
#      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
#      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=FALSW
#      - QUARKUS_LOG_LEVEL=INFO
#
#  graphqlapi:
#    image: stargateio/graphqlapi:v2.1.0-BETA-9
#    depends_on:
#      - coordinator
#    networks:
#      - stargate
#    ports:
#      - "8080:8080"
#    mem_limit: 2G
#    command: /bin/bash -c "echo 'Waiting 30s for coordinator to start first... ' && sleep 32 && java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dvertx.disableURIValidation=true -Xms256m -Xmx1024m -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar"
#    environment:
#      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
#      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
#      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=FALSE
#      - QUARKUS_LOG_LEVEL=INFO

#  docsapi:
#    image: stargateio/docsapi:v2.1.0-BETA-9
#    depends_on:
#      - coordinator
#    networks:
#      - stargate
#    ports:
#      - "8180:8180"
#    mem_limit: 2G
#    command: /bin/bash -c "echo 'Waiting 30s for coordinator to start first... ' && sleep 34 && java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dvertx.disableURIValidation=true -Xms256m -Xmx1024m -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar"
#    environment:
#      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
#      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
#      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=FALSE
#      - QUARKUS_LOG_LEVEL=INFO

  jsonapi:
    image: stargateio/jsonapi:v1.0.1
    depends_on:
      coordinator:
        condition: service_healthy
    networks:
      - stargate
    ports:
      - "8181:8181"
    mem_limit: 2G
    environment:
      #- QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      #- QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
      - STARGATE_DATA_STORE_SAI_ENABLED=true
      - STARGATE_DATA_STORE_IGNORE_BRIDGE=true
      - STARGATE_JSONAPI_OPERATIONS_DATABASE_CONFIG_CASSANDRA_END_POINTS=coordinator
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=FALSE
      - QUARKUS_LOG_LEVEL=INFO
      - JAVA_MAX_MEM_RATIO=75
      - JAVA_INITIAL_MEM_RATIO=50
      - GC_CONTAINER_OPTIONS=-XX:+UseG1GC
      - JAVA_OPTS_APPEND=-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    healthcheck:
      test: curl -f http://localhost:8181/stargate/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
networks:
  stargate:
