name: Java SDK Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Stargate with Docker
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./stargate-sdk-test/src/test/resources/docker-compose.yml"
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Test with Maven
        run: mvn test
